# Getting Started with pandas Part 1
## Book: Python for Data Analysis

In [15]:
import pandas as pd
import numpy as np

## 1) Series

A Series is a one-dimensional array-like object containing a sequence of values (similar types to NumPy types)

In [3]:
obj = pd.Series([4,7,-5,4])
obj

0    4
1    7
2   -5
3    4
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  4])

In [5]:
obj.index #like range(4)

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4,7,-5,4], index= ['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    4
dtype: int64

In [8]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['a']

-5

In [11]:
obj2['d']

4

In [12]:
obj2[['a', 'b', 'c']] #it's like in R c()

a   -5
b    7
c    4
dtype: int64

In [13]:
obj2[obj2 > 0] #logical 

d    4
b    7
c    4
dtype: int64

In [14]:
obj2*10

d    40
b    70
a   -50
c    40
dtype: int64

In [16]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      54.598150
dtype: float64

In [17]:
'b' in obj2

True

In [20]:
'e' in obj2

False

In [22]:
#The first value in a dict is the key and then the value 
sdata = {'Ohio': 3500, 'Texas': 71000, 'Oregeon': 16000, 'Utah': 500} 
sdata

{'Ohio': 3500, 'Oregeon': 16000, 'Texas': 71000, 'Utah': 500}

In [24]:
#When you are only passing a Python dictionary, the index in the resulting Series will have 
#the dict's keys in sorted order
obj3 = pd.Series(sdata)
obj3

Ohio        3500
Oregeon    16000
Texas      71000
Utah         500
dtype: int64

In [28]:
states = ['California', 'Ohio', 'Oregeon', 'Texas']
obj4 = pd.Series(sdata, index= states)
obj4

California        NaN
Ohio           3500.0
Oregeon       16000.0
Texas         71000.0
dtype: float64

In [29]:
#Identify NA in pandas

pd.isnull(obj4)


California     True
Ohio          False
Oregeon       False
Texas         False
dtype: bool

In [30]:
#Identify NA in pandas

pd.notnull(obj4)

California    False
Ohio           True
Oregeon        True
Texas          True
dtype: bool

In [31]:
obj4.isnull()

California     True
Ohio          False
Oregeon       False
Texas         False
dtype: bool

In [32]:
obj3

Ohio        3500
Oregeon    16000
Texas      71000
Utah         500
dtype: int64

In [33]:
obj4

California        NaN
Ohio           3500.0
Oregeon       16000.0
Texas         71000.0
dtype: float64

In [34]:
obj3+obj4

California         NaN
Ohio            7000.0
Oregeon        32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [36]:
#Both the Series object itself and its index have a 'name' attribute

obj4.name = 'population'
obj4


California        NaN
Ohio           3500.0
Oregeon       16000.0
Texas         71000.0
Name: population, dtype: float64

In [39]:
obj4.index.name = 'State:'
obj4

State:
California        NaN
Ohio           3500.0
Oregeon       16000.0
Texas         71000.0
Name: population, dtype: float64

## 2) Dataframes

In [41]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002, 2003],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [42]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002
5  3.2  Nevada  2003

In [43]:
frame.head()

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [44]:
frame.tail()

pop   state  year
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002
5  3.2  Nevada  2003

In [45]:
pd.DataFrame(data, columns= ['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [47]:
frame2 = pd.DataFrame(data, columns = ['year', 'state', 'pop', 'debt'], index= ['one', 'two', 'three', 'four',
                                                                               'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [49]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [50]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

Column index:

In [51]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [53]:
frame2['state']['one']

'Ohio'

In [54]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

Row index

In [55]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [57]:
frame2['debt'] = 16.5

In [58]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [61]:
frame2['debt'] = np.arange(6.) 
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [64]:
val = pd.Series([-1.2, -1.5, -1.7], index= ['two', 'four', 'five'])

frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [70]:
frame2['easter'] = frame2['state'] == 'Ohio'
frame2

year   state  pop  debt  easter
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7  -1.2    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False
six    2003  Nevada  3.2   NaN   False

Delete a column

In [71]:
del frame2['easter']

In [72]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

Another common form of data is a nested dict of dicts: First key the **columns** second key **index**

In [74]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [76]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

Transpose a DataFrame

In [77]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [79]:
#The Keys in the inner dicts are combined and sorted to form the index in the result
#This isn't true if an explicit index is specified

pd.DataFrame(pop, index= [2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [84]:
frame3['Ohio'][:-1]

2000    1.5
2001    1.7
Name: Ohio, dtype: float64

In [86]:
frame3['Nevada'][:2]

2000    NaN
2001    2.4
Name: Nevada, dtype: float64

In [88]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

Dataframe's names in: index and columns

In [91]:
#Name in index 

frame3.index.name = 'year'

frame3


Nevada  Ohio
year              
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [93]:
#Columns names

frame3.columns.name = 'state'

frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [94]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [95]:
frame3.values*10

array([[nan, 15.],
       [24., 17.],
       [29., 36.]])

In [97]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## 3) Index Objects

In [99]:
obj = pd.Series(range(3), index= ['a', 'b', 'c'])
obj

a    0
b    1
c    2
dtype: int64

In [100]:
index = obj.index

In [101]:
index

Index(['a', 'b', 'c'], dtype='object')

In [102]:
index[1:]

Index(['b', 'c'], dtype='object')

Index objects are **immutable** and thus can't be modified by the user

In [105]:
index[1] = 'd'

TypeError: Index does not support mutable operations

Immutability makes it safer to share index objects among data structures

In [107]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [109]:
obj2 = pd.Series([1.5, -2.5, 0], index= labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [110]:
obj2.index is labels

True

In [111]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [112]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [113]:
'Ohio' in frame3.columns

True

Unlike *Python Sets*, a pandas Index can contain duplicates labels:

In [115]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [119]:
dup_labels.unique()

Index(['foo', 'bar'], dtype='object')