# Getting Started with Pandas Part 3 
## Book: Python for Data Analysis  

In [1]:
import pandas as pd
import numpy as np

## 1) Arithmetic and Data Aligment

In [2]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index= ['a', 'c', 'd', 'e'])

In [3]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [5]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index= ['a', 'c', 'e', 'f', 'g'])
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [6]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

The internal **data alignment** introduces *missing values* in the label locations that don't overlap

In [8]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns=list('bcd'),
                  index= ['Ohio', 'Texas', 'Colorado'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [10]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'),
                  index= ['Utha', 'Ohio', 'Texas', 'Oregon'])
df2

b     d     e
Utha    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [11]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utha      NaN NaN   NaN NaN

In [13]:
df1 = pd.DataFrame({'A':[1,2]})
df1

A
0  1
1  2

In [15]:
df2 = pd.DataFrame({'B': [3,4]})
df2

B
0  3
1  4

In [16]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

## 2) Arithmetic methods with fill values

In [18]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns= list('abcd'))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [20]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), 
                  columns= list('abcde'))
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [23]:
df2.loc[1, 'b'] = np.nan
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [24]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In order to avoid having *NaN* we can use the **method.add(pandas_object, fill_values=0)**

In [26]:
df1.add(df2, fill_value= 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

There're a serie of arithmetic methods for Series and Dataframes: *add, sub, div, floordiv, mul, pow*. And each of them has a counterpart, starting with **r**

In [27]:
1 / df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [29]:
#It's the same as above

df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

## 3) Operations between DataFrames and Series

In [31]:
#Two-dimensional array 

arr = np.arange(12.).reshape((3,4))
arr


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [32]:
arr[0]

array([0., 1., 2., 3.])

In [33]:
#This's called broadcasting
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [35]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)), 
                    columns = list('bde'), index= ['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [38]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [39]:
#Broadcasting down the rows: 

frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [42]:
series2 = pd.Series(range(3), index= ['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [43]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

There's a problem when the indixes not are the same in the Dataframe and Series

In [45]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [47]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [53]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [49]:
#Sub= substraction (-)
frame.sub(series3, axis= 0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [51]:
frame.add(series3, axis=0)

b     d     e
Utah     1.0   2.0   3.0
Ohio     7.0   8.0   9.0
Texas   13.0  14.0  15.0
Oregon  19.0  20.0  21.0

In [52]:
#It's the same as above
frame.add(series3, axis= 'index')

b     d     e
Utah     1.0   2.0   3.0
Ohio     7.0   8.0   9.0
Texas   13.0  14.0  15.0
Oregon  19.0  20.0  21.0

## 4) Function Application and Mapping

NumPy **ufuncs** (element-wise array method) also works with pandas objects

In [69]:
np.random.seed(100)

frame = pd.DataFrame(np.random.rand(4,3), columns= list('bde'),
                    index= ['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah    0.543405  0.278369  0.424518
Ohio    0.844776  0.004719  0.121569
Texas   0.670749  0.825853  0.136707
Oregon  0.575093  0.891322  0.209202

In [70]:
np.abs(frame)

b         d         e
Utah    0.543405  0.278369  0.424518
Ohio    0.844776  0.004719  0.121569
Texas   0.670749  0.825853  0.136707
Oregon  0.575093  0.891322  0.209202

The **apply** method within pandas. The function is invoked once **on each column** in frame

In [71]:
f = lambda x: x.max() - x.min()

In [77]:
frame.apply(f, axis = 0)

b    0.301371
d    0.886603
e    0.302948
dtype: float64

In [80]:
frame.apply(f, axis = 'rows')

b    0.301371
d    0.886603
e    0.302948
dtype: float64

In [75]:
0.891322 - 0.004719

0.8866029999999999

The **apply** method within pandas. The function is invoked once **on each row** in frame

In [78]:
frame.apply(f, axis= 1)

Utah      0.265036
Ohio      0.840057
Texas     0.689146
Oregon    0.682120
dtype: float64

In [81]:
frame.apply(f, axis= 'columns')

Utah      0.265036
Ohio      0.840057
Texas     0.689146
Oregon    0.682120
dtype: float64

The function passed to apply **need not return** a **scalar value**, it can also return a Series with multiple values

In [86]:
def f(x):
    return pd.Series([x.min(),x.max()], index=['min', 'max'])

In [89]:
frame.apply(f, axis = 1)

min       max
Utah    0.278369  0.543405
Ohio    0.004719  0.844776
Texas   0.136707  0.825853
Oregon  0.209202  0.891322

Suppose you want to compute a formatted string from each floating-point value in frame. You can do this with **apply map** 

In [92]:
frame

b         d         e
Utah    0.543405  0.278369  0.424518
Ohio    0.844776  0.004719  0.121569
Texas   0.670749  0.825853  0.136707
Oregon  0.575093  0.891322  0.209202

In [90]:
format_print = lambda x: '%.2f' % x

In [91]:
frame.applymap(format_print)

b     d     e
Utah    0.54  0.28  0.42
Ohio    0.84  0.00  0.12
Texas   0.67  0.83  0.14
Oregon  0.58  0.89  0.21

The reason for name **applymap** is that Series has a **map** method for applying an element-wise function

In [94]:
frame['e'].map(format_print)

Utah      0.42
Ohio      0.12
Texas     0.14
Oregon    0.21
Name: e, dtype: object

## 5) Sorting and Ranking