# Python Numpy Tutorial
## April 23th 2018

[The information was obtained from this link](http://cs231n.github.io/python-numpy-tutorial/)

In [186]:
!python --version
!pwd

Python 3.6.4 :: Anaconda, Inc.
/Users/raziel/Jupyter


## Modules:

In [82]:
import numpy as np
from math import sqrt
import time

# Introduction

In [5]:
x=3
x +=1 
print(x)
print(type(x))

4
<class 'int'>


## 1) Lists: 
A list is the Python equivalent of an array, but it's **resizeable** and **can contain elements of different types**. Their elements can be refered by position. 

In [15]:
xs = [3,1,2]
print(xs, xs[2])
#Add a new element to the end of the list:
xs.append('bar')
print(xs)
x=xs.pop() #Remove and return the lst element of the list
print(x, xs)

[3, 1, 2] 2
[3, 1, 2, 'bar']
bar [3, 1, 2]


In [19]:
animal=['cat', 'dog', 'monkey']
print(type(animal))
for i in animal:
    print(i)

<class 'list'>
cat
dog
monkey


More sophisticated for loop

In [20]:
animals=['cat', 'dogs', 'monkey']
for id, i in enumerate(animals):
    print('#%d: %s' % (id +1, i))

#1: cat
#2: dogs
#3: monkey


List comprehensions:

In [24]:
nums=[0, 1, 2, 3, 4]
squares=[]
for i in nums:
    squares.append(i **2)
print(squares)

### You can do this code simpler using list comprehension:

nums=[0, 1, 2, 3, 4]
squares=[i ** 2 for i in nums]
print(squares)

### List comprehensions with conditions
nums=[0, 1, 2, 3, 4]
even_squares=[i ** 2 for i in nums if i % 2 == 0]
print(even_squares)
    

[0, 1, 4, 9, 16]
[0, 1, 4, 9, 16]
[0, 4, 16]


## 2) Sets

Sets are an **unordered collection** of distinct items that **don't contain duplicates**. Can be created by using name_of_the_set={}

In [57]:
animals={'cat','dog', 'cat', 'cat'}
animals.add('fish')
print(animals)

{'cat', 'dog', 'fish'}


In [48]:
#Iterating over a set has the same syntax as iterating over a list. However since sets are unordered, 
#you cannot make assumptions about the order in which you visit the elements

animals={'cat', 'dog', 'fish'}
for id, i in enumerate(animals):
    print('#%d: %s' % (id+1, i))

nums={int(sqrt(i)) for i in range(30)}
print(nums)

#1: cat
#2: dog
#3: fish
{0, 1, 2, 3, 4, 5}


## 3) Tuples
A tuple is an **immutable** ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that *tuples* **can be used as keys in dictionaries** and as **elements of sets** while list cannot. 

In [55]:
t=(5,6)
print(type(t))
### Create a dictionary with tuple keys:
dictionary={(i, i+1): i for i in range(10)}
print(dictionary)
## Using tuples as keys in dictionaries:
print(dictionary[t])
print(dictionary[(1,2)])

<class 'tuple'>
{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}
5
1


Example of **Range**:

In [79]:
#Example of range
for i in range(5):
    print(i)
print('---------')
for i in range(3,5):
    print(i)

0
1
2
3
4
---------
3
4


# Numpy

## 2) Arrays
A numpy array is a grid of values, **all of the same type**, and is indexed by a *tuple*. The number of dimensions is the rank  of the array; *the shape* of an array is *a tuple of integers* giving the size of the array along each dimension.

In [112]:
#Create a rank 1 array
a = np.array([1, 2, 3]) 
print(a)
print(type(a))
print(a.shape)

#Create a rank 2 array
b = np.array([[1,2,3], [4,5,6]])
print(b)
print(b.shape, b.dtype)
print(b[1,1])

[1 2 3]
<class 'numpy.ndarray'>
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3) int64
5


Numpy also provides many functions to create arrays

In [96]:
a =np.zeros((3,2))
print(a)
print('-------')

b=np.ones((2,3))
print(b)
print('-------')

c=np.full((3,3), 10)
print(c)
print('-------')

#Create a 3X3 identity matrix
d=np.eye(3)
print(d)
print('-------')

e=np.random.random((3,3))
print(e)
print('-------')

f=np.random.rand(3)
print(f)
print('-------')

[[0. 0.]
 [0. 0.]
 [0. 0.]]
-------
[[1. 1. 1.]
 [1. 1. 1.]]
-------
[[10 10 10]
 [10 10 10]
 [10 10 10]]
-------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-------
[[0.70356082 0.67514509 0.65820873]
 [0.87757309 0.8153093  0.27767699]
 [0.39423762 0.96172433 0.90961302]]
-------
[0.25402764 0.86837264 0.62459342]
-------


### 2.1) Array indexing

In [111]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
print(a.shape)
print("-------")
b=a[:2,1:3]
print(b)
print(a[0,1])
a[0,1]=77
print(a[0,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
-------
[[2 3]
 [6 7]]
2
[ 1 77  3  4]


You can also mix integer indexing with slice indexing. However doing so will yield an array of lower rank than the original. 

In [110]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

#Slicing by row:
print("Slicing by row:")

row_r1=a[1, :] #Rank 1
print(row_r1, row_r1.shape)

row_r2=a[1:2, :] #Rank 2
print(row_r2, row_r2.shape)

#Slicing by column:

print("Slicing by column:")

col_r1=a[:,1]
print(col_r1, col_r1.shape)
col_r2=a[:,1:2]
print(col_r2, col_r2.shape)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Slicing by row:
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
Slicing by column:
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


Integer array indexing:

In [125]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a, a.shape, a.dtype)
print("------")

#Create an array of indices:
b = np.array([2,1])
print(a[b,:])
print("------")

#Mutate the elements using the indices of 'b'
a[b,:] += 10
print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4) int64
------
[[ 9 10 11 12]
 [ 5  6  7  8]]
------
[[ 1  2  3  4]
 [15 16 17 18]
 [19 20 21 22]]


Boolean array indexing. Frequently this type of indexing is used to select the elements of an array that *satisfy some conditions*

In [131]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)

#Select the ones that are higher than 2 

boolean_index = (a > 2)
print(boolean_index)
print("------")

#When using a boolean array index we obtain a rank 1 array consisting the elements of the True values
print(a[boolean_index])

#Doing this in one step:
print(a[a > 2])


[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
------
[3 4 5 6]
[3 4 5 6]


Datatypes:

In [136]:
x = np.array([1,2])
print(x.dtype)
y=np.array([1.0,2])
print(y.dtype)

#Create a new array specifying the data-type:
y = np.array([1,2], dtype= np.float64)
print(y, y.dtype)

int64
float64
[1. 2.] float64


### 2.3) Array math

In [155]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y=np.array([[5,6], [7,8]], dtype= np.float64)

print(x, x.shape); print(y, y.shape)

#Elementwise sum:

print("\n", "Sum:"+ str(x+y), "\n", "Sum NumPy:" + str(np.add(x,y)), "\n")

#Elementwise difference:

print("Difference:" + str(x-y), "\n", "Difference NumPy:" + str(np.subtract(x,y)), "\n")

#Elementwise product:

print("Multiply:"+ str(x*y), "Multiply NumPy:" + str(np.multiply(x,y)), "\n")

#Elementwise division:

print("Divide:"+ str(x/y), "Divide NumPy:" + str(np.divide(x,y)), "\n")

#Elementwise square root:

print("Square root:"+ str(np.sqrt(x)))


[[1. 2.]
 [3. 4.]] (2, 2)
[[5. 6.]
 [7. 8.]] (2, 2)

 Sum:[[ 6.  8.]
 [10. 12.]] 
 Sum NumPy:[[ 6.  8.]
 [10. 12.]] 

Difference:[[-4. -4.]
 [-4. -4.]] 
 Difference NumPy:[[-4. -4.]
 [-4. -4.]] 

Multiply:[[ 5. 12.]
 [21. 32.]] Multiply NumPy:[[ 5. 12.]
 [21. 32.]] 

Divide:[[0.2        0.33333333]
 [0.42857143 0.5       ]] Divide NumPy:[[0.2        0.33333333]
 [0.42857143 0.5       ]] 

Square root:[[1.         1.41421356]
 [1.73205081 2.        ]]


More mathematical operations:

In [185]:
x = np.array([[1,2], [3,4]]); y = np.array([[5,6], [7,8]])
v=np.array([9,10]); w=np.array([11,12])

### Inner product of vectors
print(v.dot(w))
print(np.dot(v,w))
print(9*11+10*12, "\n")

### Matrix*vector product; rank 1 array
print(np.dot(x,v), "\n")

### Matrix*Matrix; rank 2 array:
print(np.dot(x,y), "\n")

###### Sum function

print("x:"+ str(x), "\n")

print("Sum of all x:" + str(np.sum(x)), "\n")

print("Col-sum:"+ str(np.sum(x, axis=0)), "\n")
print("Row-sum:"+ str(np.sum(x, axis=1)), "\n")


################ Transpose: 

x = np.array([[1,2], [4,5]], dtype=np.float64)

print(x, "\n")
print("Transpose:"+ str(x.T))

219
219
219 

[29 67] 

[[19 22]
 [43 50]] 

x:[[1 2]
 [3 4]] 

Sum of all x:10 

Col-sum:[4 6] 

Row-sum:[3 7] 

[[1. 2.]
 [4. 5.]] 

Transpose:[[1. 4.]
 [2. 5.]]


[Examples of more mathematical functions](https://docs.scipy.org/doc/numpy/reference/routines.math.html)

## Example of vectorization
Always try to avoid **for loops**

In [97]:
#Input data:
a=np.random.rand(1000000)
b=np.random.rand(1000000)

### 1) Vectorized version:

tic=time.time()
c=np.dot(a,b)
toc=time.time()

print(c)
print("Vectorized version:" + str(1000*(toc-tic))+"ms") # ms:miliseconds
#The code it took 1.15 ms to obtain the result

### 2) Non-vectorized version:

c=0
tic=time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc=time.time()

print(c)
print("Non-vectorized version:" + str(1000*(toc-tic)) + "ms"  )


250014.0821423447
Vectorized version:1.7211437225341797ms
250014.08214234543
Non-vectorized version:589.1139507293701ms
